config/routes.rb
Rails.application.routes.draw do
  get "search" => "search#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  resources :users, except: [:index, :new]
  resources :sessions, except:[:index, :new, :show, :edit, :update, :destroy]
  resources :globs do
      resources :comments
    end 
  resources :password_resets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    
  # Defines the root path route ("/")
  get "about" => "sites#about"
   root "sites#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :glob
    
    validates :body, presence: true
    validates :contributor, presence: true
    validates :contact, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_glob
  before_action :load_comment, except: [:index, :new, :create]
  
  def index
  end
  def new
    @comment = Comment.new
  end 
  def create
    @comment = Comment.new comment_params
    if @glob.comments << @comment
      redirect_to glob_comment_path(@glob,@comment), notice: "New Comment" 
      # Possibly need to fix this
    else
      render :new, status: :unprocessable_entity
    end
  end
  def show
  end
  
  def edit
  end
  
  def update
    if @comment.update comment_params
      redirect_to glob_comment_path(@glob,@comment), notice: "Comment Updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to glob_comments_path(@glob), alert: "Comment Deleted"
  end
  
  private 
  
  def comment_params
    params.require(:comment).permit(:body,:contributor,:contact)
  end
  
  def load_comment
    @comment = @glob.comments.find params[:id]
  end
  
  def load_glob
    @glob = Glob.find params[:glob_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
    <div id="<%= dom_id(comment)%>" class="comment border border-dark rounded">
        <p><strong>Comment: </strong><%= comment.body%></p>
        <p><strong>By: </strong><%= link_to_unless_current comment.contributor, glob_comment_path(@glob,comment)%></p>
        <p><strong>Contact Information: </strong><%= comment.contact%></p>
    </div>

app/views/comments/_form.html.erb
<%=bootstrap_form_with(model: [@glob,@comment]) do |f|%>
    <%= f.alert_message "Comment Could Not Be Created ERRORS", error_summary: false%>
    <%= f.text_area :body %>
    <%= f.text_field :contributor%>
    <%= f.text_field :contact %>
    <%= f.primary @comment.persisted? ? 'Edit Comment' : 'Generate Comment' %>
<% end %>

app/views/comments/edit.html.erb
<%= title "Edit Comment for "+@glob.title%>

<%= render 'form' %>

app/views/comments/index.html.erb
<%= title "Comments for "+@glob.title%>

<%= render @glob.comments%>

<%= link_to "New Comment", new_glob_comment_path(@glob), class: "btn btn-primary"%>
</br>
<%= link_to "Back to Glob ", glob_path(@glob)%>

app/views/comments/new.html.erb
<%= title "New Comment for " +@glob.title%>

<%= render 'form' %>

app/views/comments/show.html.erb
<%= title "Comment for "+@glob.title%>

<%= render @comment %>

<%= link_to "Edit Comment", edit_glob_comment_path(@glob,@comment)%> | <%= link_to "Comments", glob_comments_path(@glob)%>
</br>
<%= button_to 'Delete Comment', [@glob,@comment], method: :delete, class: 'btn btn-danger', form: {data: {turbo_confirm: "Are you sure?"} } %>