config/routes.rb
Rails.application.routes.draw do
  get "search" => "search#index"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  get "logout" => "sessions#destroy"
  get "/auth/:provider/callback" => "authentications#create"
  resources :users, except: [:index, :new]
  resources :sessions, except:[:index, :new, :show, :edit, :update, :destroy]
  resources :globs do
      resources :comments
    end 
  resources :password_resets
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
    
  # Defines the root path route ("/")
  get "about" => "sites#about"
   root "sites#index"
end

app/models/glob.rb
class Glob < ApplicationRecord
    belongs_to :user
    has_many :comments
    
    validates :title, presence: true
    validates :summary, presence: true
    validates :author, presence: true
end

app/controllers/globs_controller.rb
class GlobsController < ApplicationController
  before_action :authenticate
  before_action :load_glob, except: [:new, :index, :create]
  #GET all globs
  def index
    @globs = Glob.all
  end
  #GET glob
  def new
    @glob = Glob.new
  end
  #POST a new glob
  def create
  @glob = Glob.new glob_params
  @glob.user = current_user
  if @glob.save
    redirect_to globs_path, notice: "Glob Successfully Created"
  else
    render :new, status: :unprocessable_entity
  end
  end
  #GET glob
  def show
  end
  #GET glob
  def edit
    #add if logic for if the user is equal to current user else redirect to root
    if @glob.user != current_user
      redirect_to root_path, notice: "Invalid request"
    end
  end
  #PATCH/PUT glob
  def update
    if @glob.user == current_user
      if @glob.update glob_params
        redirect_to @glob, notice: "Glob Successfully Updated"
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to root_path, alert: "Invalid request"
    end
  end
  #DELETE glob
  def destroy
    # add same if logic like above
    if @glob.user == current_user
      @glob.destroy
      redirect_to globs_path, alert: "Glob was Deleted!"
    else
       redirect_to root_path, alert: "Invalid request"
    end
  end
  
  private
  
  def load_glob
    @glob = Glob.find params[:id]
  end
  def glob_params
    params.require(:glob).permit(:title,:summary,:author)
  end
  
end

app/helpers/globs_helper.rb
module GlobsHelper
end

app/views/globs/_form.html.erb
<%=bootstrap_form_with(model: @glob) do |f|%>
    <%= f.alert_message "Glob Could Not Be Created ERRORS", error_summary: true%>
    <%= f.text_field :title %>
    <%= f.text_field :summary %>
    <%= f.text_field :author %>
    <%= f.primary @glob.persisted? ? 'Edit Glob' : 'Create Glob' %>
<% end %>

app/views/globs/_glob.html.erb
<div id="<%= dom_id(glob)%>" class="glob border border-dark rounded">
    <p><strong>Title: </strong><%= link_to_unless_current glob.title, glob%></p>
    <p><strong>Summary: </strong><%= glob.summary%></p>
    <p><strong>Author: </strong><%= glob.author%></p>
</div>

app/views/globs/edit.html.erb
<%= title "Edit Glob" %>

<%= render 'form'%>

app/views/globs/index.html.erb
<%= title "Globs" %>
<%@globs.each do |glob|%>
    <%= render glob %>
<% end %>

<P>
    <%= link_to "New Glob", new_glob_path, class: "btn btn-primary"%>
</P>

app/views/globs/new.html.erb
<%= title "Create Your Next Glob" %>

<%= render 'form'%>

app/views/globs/show.html.erb
<%= title "View Glob" %>

<%= render @glob %>
<% if @glob.user == current_user%>
<%= link_to "Edit Glob", edit_glob_path(@glob)%> 
<%= button_to 'Delete Glob', @glob, method: :delete, class: 'btn btn-danger', form: {data: {turbo_confirm: "Are you sure?"} } %>
<%end%>
| <%= link_to "All Globs", globs_path%> | <%= link_to "Comments", glob_comments_path(@glob)%>